version: 2.1
orbs:
  node: circleci/node:10.14-browsers
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
store_test_results:
          path: /tmp/test-results